- name: Configure Managed Nodes
  hosts: worker
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Copy application archive
      copy:
        src: app.tar.gz
        dest: /home/ubuntu/app.tar.gz

    - name: Extract application
      unarchive:
        src: /home/ubuntu/app.tar.gz
        dest: /home/ubuntu/
        remote_src: yes

    - name: Deploy application using Docker Compose
      shell: |
        cd /home/ubuntu/app
        docker-compose up -d

